### ISSUE TITLE
frontpanel lib not working on 64-bit platforms

### ISSUE THREAD

**Issue by lexthehex** [samplx/z80pack#1]
To get the frontpanel library to work on a 64-bit platform, you will need to disable optimisation for the library.  Edit frontpanel/Makefile and in the CFLAGS line, change -O3 to -O0.  The library will then work.

**Comment by samplx** [comment]
Sorry for the very late reply. This repo is being archived. 

I am sure that the original author has corrected the issues.

You should use [his code](https://github.com/udo-munk/z80pack) if you haven't already.
